stages:
  - test
  - build
  - register

test-all:
  stage: test
  image: maven:3.9.7-eclipse-temurin-22-alpine
  script: mvn clean test

build-job:
  stage: build
  image: maven:3.9.7-eclipse-temurin-22-alpine
  script: mvn clean package
  artifacts:
    paths:
      - target/reservation-services.jar

register:
  stage: register
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - echo "$TOKEN" | docker login registry.gitlab.com -u $CI_REGISTRY_USER --password-stdin
    - docker build -t registry.gitlab.com/cherrychainstage/reservation-services .
    - docker push registry.gitlab.com/cherrychainstage/reservation-services
