stages:
  - test
  - build

test-all:
  stage: test
  image: maven:3.9.7-eclipse-temurin-22-alpine
  script: mvn clean test

build-job:
  stage: build
  image: maven:3.9.7-eclipse-temurin-22-alpine
  script: mvn clean package
  artifacts:
    paths:
      - target/reservation-services.jar