services:
  server:
    image: registry.gitlab.com/cherrychainstage/reservation-services
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=reservations
      - POSTGRES_PASSWORD=password