services:
  server:
    image: registry.gitlab.com/cherrychainstage/reservation-services
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reservations
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password