server:
  port: 8080
  host: 0.0.0.0

app:
    groupId: com.cherry.fm.reservationservices
    artifactId: cherry-manning
    version: 0.1
    greeting: "Hello"

db:
  source: jdbc
  connection:
    url: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    initializationFailTimeout: -1
    connectionTimeout: 2000
  health-check:
    type: "query"
    statementName: "health-check"
